export const skillsAttributes = [
    { title: "Acrobacia", simbolo: "+" },
    { title: "Adestramento", simbolo: "*" },
    { title: "Atletismo" },
    { title: "Atuação" },
    { title: "Cavalgar" },
    { title: "Conhecimento", simbolo: "*" },
    { title: "Cura" },
    { title: "Diplomacia" },
    { title: "Enganação" },
    { title: "Fortitude" },
    { title: "Furtividade", simbolo: "+" },
    { title: "Guerra", simbolo: "*" },
    { title: "Iniciativa" },
    { title: "Intimidação" },
    { title: "Intuição" },
    { title: "Investigação" },
    { title: "Jogatina", simbolo: "*" },
    { title: "Ladinagem", simbolo: "*", simbolo2: "+" },
    { title: "Luta" },
    { title: "Misticismo", simbolo: "*" },
    { title: "Nobreza", simbolo: "*" },
    { title: "Ofício", simbolo: "*" },
    { title: "Ofício", simbolo: "*" },
    { title: "Percepção" },
    { title: "Pilotagem", simbolo: "*" },
    { title: "Pontaria" },
    { title: "Reflexos" },
    { title: "Religião", simbolo: "*" },
    { title: "Sobrevivência" },
    { title: "Vontade" },
  ];